spring.application.name=prompt-review-service

server.port=8001

# Directory where review JSON files will be stored
review.storage.path=reviews

# Prompt Service URL
prompt.service.url=http://localhost:8000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html